### ISSUE TITLE
Problem about the datasets

### ISSUE THREAD

**Issue by JingYu22** [jinnh/PDE-Net#1]
Hello, @jinnh !
I found that in the given code, the path of the datasets seemed to be '/datasets/HSI/CAVE/' or /datasets/HSI/Harvard/, but there are no corresponding folders. I wonder if the datasets are available?

**Comment by jinnh** [comment]
Hello, @JingYu22! Thank you for your interest in our work.

We have updated the file 'README.md', you can download the datasets from the corresponding links, and run the matlab programs in the folder 'datasets' to get the pre-processed training and testing data.
